// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { defineConfig } from 'prisma/config';

dotenv.config();

if (!process.env.DATABASE_URL) {
  throw new Error(
    'DATABASE_URL is missing (required for prisma migrate deploy).',
  );
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node-dev prisma/seed.ts',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
